name: Build and deploy Rmd to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install R packages
        run: Rscript -e 'install.packages(c("rmarkdown","postcards"), repos="https://cloud.r-project.org")'

      - name: Render index.Rmd
        run: |
          mkdir -p dist
          Rscript -e 'rmarkdown::render("index.Rmd", output_file = "index.html", output_dir = "dist")'
          # safely copy assets only if they exist
          if [ -f "IMG_1104.JPG" ]; then cp IMG_1104.JPG dist/; fi
          if [ -d "img" ]; then cp -R img dist/; fi
          if [ -d "HW1" ]; then cp -R HW1 dist/; fi

      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4

